package com.example.bankingappmod.ui.theme

const val Account = "Account"
const val RecentTransactions = "Recent Transactions"
const val ViewAll = "VIEW ALL"
const val Add = "Add"

const val Transaction = "Transaction"
const val TrApplied = "Transaction was applied in"
const val TrNumber = "Transaction number"
const val TrStatus = "Transaction status"
const val Amount = "Amount"
const val Date = "Date"

const val accountScreen = "account_screen"
const val addTransactionScreen = "add_transaction_screen"
const val allTransactionsScreen = "all_transactions_screen"
const val transactionDetailScreen = "transaction_detail_screen"
const val selectAccountScreen = "select_account_screen"
const val filterScreen = "filter_screen"
const val Okay = "Okay"
const val FilterByDate = "Filter by date"
const val StartDate = "Start Date"
const val EndDate = "End Date"
const val Submit = "Submit"
